### ISSUE TITLE
transfer to an org

### ISSUE THREAD

**Issue by afeld** [cloudfoundry-community/rds-broker#1]
Either @18F or @cloudfoundry-community. Can we still make it CC0 if using the latter?

/cc https://trello.com/c/umB6C7Iv/85-as-an-18f-er-i-want-to-contribute-to-cloud-foundry

**Comment by dlapiduz** [comment]
@afeld I am going to move it to cloudfoundry-community as soon as it actually creates the RDS instances... I kept it here for know to avoid any issues.
